name: Discover dependencies via `renovate-graph` and upload via the Dependency Submission API

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  SBOM-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: stable

      - name: Install `renovate-to-sbom`
        run: |
          go install dmd.tanna.dev/cmd/renovate-to-sbom@latest

      - name: Retrieve package data with renovate-graph
        run: |
          # `--platform local` and the `RG_LOCAL_` environment variables are
          # further documented in
          # https://www.jvt.me/posts/2023/10/13/renovate-graph-local/ and improve
          # the speed of dependency scanning
          npx @jamietanna/renovate-graph@latest --platform local
        env:
          # As well as looking for pending updates, this also resolves version
          # constraints such as `~= 0.3` to `0.3.1`
          RG_INCLUDE_UPDATES: true

          # variables for `--platform local`
          RG_LOCAL_PLATFORM: github
          RG_LOCAL_ORGANISATION: dagger
          RG_LOCAL_REPO: dagger

      - name: Generate SBOM
        run: |
          renovate-to-sbom out/github-dagger-dagger.json --out-format spdx2.3+json --only-include-known-purl-types

      - uses: actions/upload-artifact@v4
        with:
          name: out
          path: out

      - name: SBOM upload
        uses: advanced-security/spdx-dependency-submission-action@v0.0.1
        with:
          filePath: out
          filePattern: github-dagger-dagger.json.spdx2.3.json
